version: '3.7'
services:
  go:
    build: .
    environment:
      - APP_NAME=myapp
    volumes:
      - ./myapp:/go/src/myapp
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    container_name: gogo
    command: go run /go/src/myapp/main.go
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgresdb
    volumes: 
      - ./init:/docker-entrypoint-initdb.d


